function create_data_package(pathname,filename)
%CREATE_DATA_PACKAGE Stores all variables in pathname/filename
%   to their corrseponding cur variables in the base workspace.
%   Most of the function can be autocreated by using the desired
%   samp.m file with VARNAMES=$(cat $1 | cut -d '=' -f 1) in bash
%   (cf. assign_loop.sh)
    file=fullfile(pathname,filename);
    run(file);
    assignin('base','N_cur',N)
    assignin('base','Tmax_cur',Tmax)
    assignin('base','averaging_times_cur',averaging_times)
    assignin('base','rbin_cur',rbin)
    assignin('base','qbin_cur',qbin)
    assignin('base','H_cur',H)
    assignin('base','H_2_cur',H_2)
    assignin('base','W_cur',W)
    assignin('base','W_2_cur',W_2)
    assignin('base','M_cur',M)
    assignin('base','M_2_cur',M_2)
    assignin('base','M_4_cur',M_4)
    assignin('base','absM_cur',absM)
    assignin('base','Theta_cur',Theta)
    assignin('base','temperature_cur',temperature)
    assignin('base','abs_vortices_cur',abs_vortices)
    assignin('base','signed_vortices_cur',signed_vortices)
    assignin('base','mxq_cur',mxq)
    assignin('base','myq_cur',myq)
%     eql = eq;
%     assignin('base','eq_cur',eql)
    assignin('base','wq_cur',wq)
    assignin('base','chimxq_cur',chimxq)
    assignin('base','chimyq_cur',chimyq)
    assignin('base','chieq_cur',chieq)
    assignin('base','chiwq_cur',chiwq)
    assignin('base','SCF_Spin_cur',SCF_Spin)
    assignin('base','SCF_anglediff_cur',SCF_anglediff)
    assignin('base','TCF_times_cur',TCF_times)
    assignin('base','ACF_Spin_cur',ACF_Spin)
    assignin('base','ACF_anglediff_cur',ACF_anglediff)
    assignin('base','gxx_cur',gxx)
    assignin('base','gxy_cur',gxy)
    assignin('base','gxw_cur',gxw)
    assignin('base','gxe_cur',gxe)
    assignin('base','gyy_cur',gyy)
    assignin('base','gyw_cur',gyw)
    assignin('base','gye_cur',gye)
    assignin('base','gww_cur',gww)
    assignin('base','gwe_cur',gwe)
    assignin('base','gee_cur',gee)
    assignin('base','H_av_cur',H_av)
    assignin('base','H_2_av_cur',H_2_av)
    assignin('base','H_var_cur',H_var)
    assignin('base','W_av_cur',W_av)
    assignin('base','W_2_av_cur',W_2_av)
    assignin('base','W_var_cur',W_var)
    assignin('base','M_av_cur',M_av)
    assignin('base','M_2_av_cur',M_2_av)
    assignin('base','M_4_av_cur',M_4_av)
    assignin('base','M_var_cur',M_var)
    assignin('base','Binder_cum_cur',Binder_cum)
    assignin('base','absM_av_cur',absM_av)
    assignin('base','Theta_av_cur',Theta_av)
    assignin('base','temperature_av_cur',temperature_av)
    assignin('base','abs_vortices_av_cur',abs_vortices_av)
    assignin('base','signed_vortices_av_cur',signed_vortices_av)
    assignin('base','mxq_av_cur',mxq_av)
    assignin('base','myq_av_cur',myq_av)
    assignin('base','eq_av_cur',eq_av)
    assignin('base','wq_av_cur',wq_av)
    assignin('base','chimxq_av_cur',chimxq_av)
    assignin('base','chimyq_av_cur',chimyq_av)
    assignin('base','chieq_av_cur',chieq_av)
    assignin('base','chiwq_av_cur',chiwq_av)
    assignin('base','SCF_Spin_av_cur',SCF_Spin_av)
    assignin('base','SCF_anglediff_av_cur',SCF_anglediff_av)
end